from __future__ import annotations
import asyncio, logging, os, shutil, subprocess, tempfile
from datetime import datetime
from pathlib import Path
from aiogram.types import FSInputFile
from . import errorlog

log = logging.getLogger("tgbot")

def atomic_write(path, text):
    path = Path(path)
    path.parent.mkdir(parents=True, exist_ok=True)
    tmp = path.with_suffix(path.suffix + ".tmp")
    tmp.write_text(text, encoding="utf-8")
    os.replace(tmp, path)

def index_path(cfg): return os.path.join(cfg.config_dir, "anims_index.json")
def anims_dir(cfg): return os.path.join(cfg.config_dir, "anims")

def ensure_backup_dir(cfg):
    Path(cfg.backup_dir).mkdir(parents=True, exist_ok=True)

def load_index(cfg):
    p = index_path(cfg)
    if os.path.exists(p):
        try:
            import json
            with open(p, encoding="utf-8") as f:
                idx = json.load(f)
            if isinstance(idx, dict) and isinstance(idx.get("items"), list):
                idx.setdefault("next_id", 1)
                idx.setdefault("default", None)
                return idx
        except Exception as e:
            log.error("cannot load animation index: %s", e)
    return {"next_id": 1, "items": [], "default": None}

def save_index(cfg, idx):
    import json
    atomic_write(index_path(cfg), json.dumps(idx, ensure_ascii=False, indent=2))

def num_to_prefix(n):
    s = ""
    while n > 0:
        n, rem = divmod(n - 1, 26)
        s = chr(ord("a") + rem) + s
    return s or "a"

def regen_stop_all(cfg, idx):
    lines = ["# generated by tgbot", "[gcode_macro ANIMS_STOP_ALL]", "gcode:"]
    for it in idx["items"]:
        lines.append(f"    {it['prefix'].upper()}_STOP")
    lines.append("    SET_DISPLAY_GROUP GROUP=_default_16x4")
    atomic_write(os.path.join(anims_dir(cfg), "_stop_all.cfg"), "\n".join(lines) + "\n")

def regen_autostart(cfg, idx):
    d = idx.get("default")
    path = os.path.join(anims_dir(cfg), "_autostart.cfg")
    if d:
        atomic_write(path, f"[delayed_gcode anim_boot]\ninitial_duration: 2.0\ngcode:\n    {d.upper()}_START\n")
    else:
        atomic_write(path, "# no default animation\n")

def snapshot_anims(cfg) -> Path:
    ensure_backup_dir(cfg)
    src = Path(anims_dir(cfg))
    stamp = datetime.now().strftime("%Y%m%d_%H%M%S_%f")
    dst = Path(cfg.backup_dir) / stamp
    dst.mkdir(parents=True, exist_ok=False)
    if src.exists():
        for p in src.iterdir():
            target = dst / p.name
            if p.is_dir(): shutil.copytree(p, target)
            else: shutil.copy2(p, target)
    idx = Path(index_path(cfg))
    if idx.exists(): shutil.copy2(idx, dst / "_index.json")
    return dst

def latest_backup(cfg) -> Path | None:
    root = Path(cfg.backup_dir)
    if not root.exists(): return None
    dirs = sorted([p for p in root.iterdir() if p.is_dir()])
    return dirs[-1] if dirs else None

def rollback_anims(cfg, backup: Path | None = None):
    backup = backup or latest_backup(cfg)
    if backup is None or not backup.exists():
        raise RuntimeError("резервная копия анимаций не найдена")
    target = Path(anims_dir(cfg))
    target.mkdir(parents=True, exist_ok=True)
    for p in target.iterdir():
        if p.is_file() or p.is_symlink(): p.unlink()
        elif p.is_dir(): shutil.rmtree(p)
    for p in backup.iterdir():
        if p.name == "_index.json": continue
        dest = target / p.name
        if p.is_dir(): shutil.copytree(p, dest)
        else: shutil.copy2(p, dest)
    idx = backup / "_index.json"
    if idx.exists(): shutil.copy2(idx, index_path(cfg))

def cleanup_backups(cfg, keep=None):
    root = Path(cfg.backup_dir)
    if not root.exists(): return
    keep = max(1, int(keep or cfg.animation_backup_keep))
    dirs = sorted([p for p in root.iterdir() if p.is_dir()])
    for p in dirs[:-keep]:
        shutil.rmtree(p, ignore_errors=True)

def clean_preview(cfg):
    for e in (".gif", ".png"):
        p = Path(str(cfg.preview_base) + e)
        if p.exists():
            p.unlink()

def convert_params(cfg, src, out_cfg, prefix, s, preview_base=None):
    cmd = [
        cfg.python, cfg.converter, src, "-o", out_cfg, "--prefix", prefix,
        "--mode", s["mode"], "--auto-fill", f"{s['fill']:.2f}", "--fit", s["fit"],
        "--max-frames", str(s["frames"]), "--max-glyphs", str(cfg.max_glyphs),
        "--max-input-frames", str(cfg.animation_max_input_frames),
        "--max-input-pixels", str(cfg.animation_max_input_pixels),
        "--max-duration-ms", str(cfg.animation_max_duration_ms),
        "--ffmpeg-timeout", str(cfg.animation_ffmpeg_timeout),
    ]
    if s["invert"]:
        cmd.append("--invert")
    if preview_base:
        cmd += ["--preview-out", preview_base]
    try:
        p = subprocess.run(cmd, capture_output=True, text=True, timeout=120)
        return p.returncode, (p.stdout + p.stderr).strip()
    except subprocess.TimeoutExpired as e:
        out = ((e.stdout or "") if isinstance(e.stdout, str) else "").strip()
        return 124, f"Превышен таймаут конвертера (120 с). {out}".strip()

def caption_text(s):
    return (
        f"«{s['name']}»\nЗаливка {s['fill']:.2f} · "
        f"Инверсия {'вкл' if s['invert'] else 'выкл'} · {s['mode']} · "
        f"{s['fit']} · кадров {s['frames']}\nНастройте и нажмите «✅ Загрузить»"
    )

async def refresh_preview(bot, cfg, chat, s):
    from .ui import preview_kb
    preview_dir = Path(tempfile.mkdtemp(prefix=f"tgbot_preview_{chat}_"))
    out_cfg = preview_dir / "preview.cfg"
    preview_base = preview_dir / "preview"
    try:
        rc, out = await asyncio.to_thread(
            convert_params, cfg, s["src"], str(out_cfg), "prev", s, str(preview_base)
        )
        if rc != 0:
            eid = await errorlog.register_async(cfg, "converter", out, out, filename=s.get("name"))
            s["last_error_id"] = eid
            await bot.send_message(chat, f"❌ Ошибка конвертации #{eid}:\n{out}")
            return False

        if s.get("msg_id"):
            try: await bot.delete_message(chat, s["msg_id"])
            except Exception: pass
        kbc = preview_kb(s)
        gifp, pngp = Path(str(preview_base) + ".gif"), Path(str(preview_base) + ".png")
        try:
            if gifp.exists():
                m = await bot.send_animation(chat, FSInputFile(gifp), caption=caption_text(s), reply_markup=kbc)
            elif pngp.exists():
                m = await bot.send_photo(chat, FSInputFile(pngp), caption=caption_text(s), reply_markup=kbc)
            else:
                await bot.send_message(chat, "Нет предпросмотра.")
                return False
            s["msg_id"] = m.message_id
            return True
        except Exception as e:
            eid = await errorlog.register_async(cfg, "telegram", str(e), repr(e), filename=s.get("name"))
            await bot.send_message(chat, f"❌ Ошибка отправки превью #{eid}: {e}")
            return False
    finally:
        shutil.rmtree(preview_dir, ignore_errors=True)

async def restart_and_wait(pc, timeout=40):
    r = await pc.restart()
    if not r.ok:
        return False, r.error
    await asyncio.sleep(3)
    for _ in range(timeout):
        info = await pc.info()
        if info.get("state") == "ready":
            return True, None
        await asyncio.sleep(1)
    return False, "Klipper не перешёл в ready"

async def apply_session(bot, cfg, chat, s, pc, safety):
    ok, reason = await safety.require_idle(pc)
    if not ok:
        await bot.send_message(chat, f"❌ Нельзя загрузить анимацию: {reason}")
        return False

    idx = load_index(cfg)
    num = int(idx["next_id"])
    prefix = num_to_prefix(num)
    final_cfg = Path(anims_dir(cfg)) / f"anim_{num:03d}.cfg"
    temp_cfg = Path(anims_dir(cfg)) / f".tgbot_anim_{chat}_{num:03d}.cfg.tmp"
    backup = None

    try:
        os.makedirs(anims_dir(cfg), exist_ok=True)

        # Convert first: failed conversion must NOT create a permanent backup.
        rc, out = await asyncio.to_thread(convert_params, cfg, s["src"], str(temp_cfg), prefix, s)
        if rc != 0:
            eid = await errorlog.register_async(cfg, "converter", out, out, filename=s.get("name"))
            await bot.send_message(chat, f"❌ Ошибка конвертации #{eid}:\n{out}")
            return False

        # Snapshot immediately before the first real filesystem mutation.
        backup = snapshot_anims(cfg)
        try:
            os.replace(temp_cfg, final_cfg)
        except OSError as exc:
            if getattr(exc, "errno", None) != 18:
                raise
            # Cross-device fallback: copy atomically via a same-filesystem temp file.
            staging = final_cfg.with_suffix(final_cfg.suffix + ".tmp")
            try:
                shutil.copy2(temp_cfg, staging)
                os.replace(staging, final_cfg)
            finally:
                if staging.exists():
                    staging.unlink()

        idx["items"].append({"prefix": prefix, "name": s["name"], "file": final_cfg.name})
        idx["next_id"] = num + 1
        save_index(cfg, idx)
        regen_stop_all(cfg, idx)
        regen_autostart(cfg, idx)

        await bot.send_message(chat, "Перезапускаю Klipper…")
        ready, err = await restart_and_wait(pc)
        if not ready:
            rollback_anims(cfg, backup)
            old = load_index(cfg)
            regen_stop_all(cfg, old)
            regen_autostart(cfg, old)
            await restart_and_wait(pc)
            eid = await errorlog.register_async(cfg, "animation", f"restart: {err}", err, filename=s.get("name"))
            await bot.send_message(chat, f"❌ Рестарт не удался — выполнен откат #{eid}.\n{err}")
            return False

        start = await pc.gcode(f"{prefix.upper()}_START")
        if not start.ok:
            eid = await errorlog.register_async(cfg, "animation", start.error or "start failed",
                                                 str(start.raw or ""), filename=s.get("name"))
            await bot.send_message(chat, f"⚠️ Анимация загружена, но не запустилась #{eid}: {start.error}")
        else:
            await bot.send_message(chat, f"Готово, «{s['name']}» в меню анимаций.")

        cleanup_backups(cfg)
        return True

    except Exception as e:
        try:
            if backup:
                rollback_anims(cfg, backup)
                old = load_index(cfg)
                regen_stop_all(cfg, old)
                regen_autostart(cfg, old)
        except Exception as rollback_exc:
            log.exception("animation rollback failed: %s", rollback_exc)
        eid = await errorlog.register_async(cfg, "animation", str(e), repr(e), filename=s.get("name"))
        await bot.send_message(chat, f"❌ Ошибка установки анимации #{eid}: {e}")
        return False
    finally:
        try:
            if temp_cfg.exists(): temp_cfg.unlink()
        except Exception:
            pass
        cleanup_backups(cfg)
